=== Mohdjunaid09/shopping-cart-app/bookstore-xml/bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="bookstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="price" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="category" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Mohdjunaid09/shopping-cart-app/bookstore-xml/bookstore_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="./bookstore.xsd">

    <book category="programming">
        <title>Learn Java</title>
        <author>James Gosling</author>
        <price>500</price>
    </book>

    <book category="web">
        <title>HTML Basics</title>
        <author>Tim Berners-Lee</author>
        <price>500</price>
    </book>

</bookstore>
